[banco]
192.168.56.101
192.168.56.102
192.168.56.103


[cluster]
# 189.39.218.225
server1.librecode.coop ansible_ssh_private_key_file=~/.ssh/pop/suzi-pve01 remote_user=root
# 187.57.255.128
server2.librecode.coop ansible_ssh_private_key_file=~/.ssh/pop/lisa-pve02 remote_user=root

