---
- name: Criando os diretórios
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /var/lib/garage/meta
    - /var/lib/garage/data
    - "{{ garage_config_dir }}"

- name: Copiando a configuração do garage
  ansible.builtin.template:
    src: garage.toml.j2
    dest: "{{ garage_config_dir }}/garage.toml"
    mode: '0644'

- name: Copiando arquivo docker compose 
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ garage_config_dir }}/compose.yml"
    mode: '0644'

- name: Iniciando serviço garage
  community.docker.docker_compose_v2:
    project_src: "{{ garage_config_dir }}"
    pull: yes
    state: present