services:
  autobase-console:
    image: autobase/console:latest
    container_name: autobase-console
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - PG_CONSOLE_API_URL=http://localhost:8080/api/v1
      - PG_CONSOLE_AUTHORIZATION_TOKEN=secret_token
      - PG_CONSOLE_DOCKER_IMAGE=autobase/automation:latest
    volumes:
      - console_postgres:/var/lib/postgresql
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/ansible:/tmp/ansible
    restart: unless-stopped

volumes:
  console_postgres:

