# Diretório onde os bricks serão criados
glusterfs_brick_dir: /data/brick5

# Nome dos volume GlusterFS
glusterfs_volume_name: gv5

# Número de réplicas = número de servidores (o melhor é ter 3)
# Levar em consideração problemas de split-brain
# https://docs.gluster.org/en/main/Administrator-Guide/Split-brain-and-ways-to-deal-with-it/
glusterfs_replica_count: 2

# Diretório de montagem local
glusterfs_mount_point: /mnt/gluster-data5

# IPs de clientes permitidos que podem montar o volume
allowed_ips: "189.39.218.225,187.57.255.128,192.168.56.246"

# Lista de servidores GlusterFS (nomes ou IPs)
glusterfs_servers:
  - server2.librecode.coop
  - server1.librecode.coop



