# roles/fail2ban/tasks/main.yml
- name: Instalar pacotes necessários
  ansible.builtin.apt:
    name:
      - fail2ban
      - bind9-utils
    state: present
    update_cache: yes
  when: fail2ban_enable

- name: Criar arquivo de configuração jail.local
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  when: fail2ban_enable
  notify: Reiniciar Fail2Ban

- name: Criar arquivo de configuração route.local
  ansible.builtin.template:
    src: route.local.j2
    dest: /etc/fail2ban/action.d/route.local
    owner: root
    group: root
    mode: '0644'
  when: fail2ban_enable
  notify: Reiniciar Fail2Ban

- name: Habilitar e iniciar o serviço Fail2Ban
  ansible.builtin.service:
    name: fail2ban
    enabled: yes
    state: started
  when: fail2ban_enable