# tasks/main.yml
---
- name: Cria diretório do Traefik
  ansible.builtin.file:
    path: "{{ traefik_dir }}"
    state: directory
    mode: '0755'

- name: Copia compose.yml do Traefik
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ traefik_dir }}/compose.yml"
    mode: '0644'

- name: Inicia Traefik com docker-compose
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_dir }}/"
    state: present
    remove_orphans: true

